# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_redpul_wrappers", use_symbols = TRUE, package_name = "redpul")

#' @docType package
#' @usage NULL
#' @useDynLib redpul, .registration = TRUE
NULL

#' @export
redpul_find <- function(dataset) .Call(wrap__redpul_find, dataset)

#' @export
redpul_find_author <- function(dataset) .Call(wrap__redpul_find_author, dataset)
